export const constants = {
  DEFAULT_LANGUAGE: "ar",
  PAGE_TITLE_PREFIX: "Home",
  REDIRECT_AFTER_LOGIN: "/",
  MIN_LENGTH_TEXT_INPUT: 8,
  MAX_LENGTH_TEXT_INPUT: 191,
  MAX_LENGTH_TEXTAREA: 16777215,
  TABLE_ROWS_LENGTH: 10,
  DATA_LIMIT: 10,
}
