export const constants = {
  DEFAULT_LANGUAGE: 'ar',
  PAGE_TITLE_PREFIX: 'luluatalshifaa',
  MIN_LENGTH_TEXT_INPUT: 8,
  MAX_LENGTH_TEXT_INPUT: 191,
  MAX_LENGTH_TEXTAREA: 16777215,
  DATA_LIMIT: 12,
};
